version: "3.9"
services:
  bigproject-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"     # 포트 충돌 피하기 위해 다른 호스트 포트
      - "7767:7767"
    volumes:
      - ./save_original:/app/save_original
      - ./pdf_results:/app/pdf_results
      - ~/.cache/pip:/root/.cache/pip
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    stdin_open: true
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
              
  redis:
    image: redis:7
    ports:
      - "6379:6379"